version: '3.9'

services:
  kafka:
    command:
      - redpanda
      - start
      - --smp
      - "1"
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    # NOTE: Please use the latest version here!
    image: vectorized/redpanda
    container_name: redpanda
    ports:
      - 9092:9092
      - 29092:29092
  database:
    image: postgres
    restart: always
    container_name: database
    ports:
      - 5432:5432
    env_file:
      - ./services/.env
  api:
    container_name: api
    ports:
    - "3001:3001"
    restart: unless-stopped
    build: ./backend
  